{% set name = "uplot-python" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uplot_python-{{ version }}.tar.gz
  sha256: baa996be76451fdebfa17128db1d4ef87b523e951a1e8d2bd3e8413e517cf6e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - ipython >=8.0.1
    - msgpack-python >=1.0.4
    - numpy >=1.15.4

test:
  imports:
    - uplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/uplot-python
  summary: Python wrapper for μPlot time series.
  dev_url: https://github.com/stephane-caron/uplot-python
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
